[package]
name = "LP"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsodium-sys = "0.2.7"
libc = "0.2.139"
base64 = "0.21.0"
sodiumoxide = "0.2.7"
